title: "Query64-Rails"
description: "Documentation"
theme: just-the-docs
markdown: kramdown
color_scheme: dark
baseurl: "/Query64-Rails"
mermaid:
  version: "9.1.3"
callouts:
  warning:
    title: Attention
    color: red
  important:
    title: Important
    color: blue
  highlight:
    color: yellow
  new:
    title: Nouveau
    color: green
  note:
    title: Note
    color: purple
aux_links:
  Voir sur Github:
    - https://github.com/CHUReimsDSN/Query64-Rails